version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  app:
    build: .
    cpus: 1
    mem_limit: 256M
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - app
