version: "3"

services:
  app:
    container_name: app
    build: .
    cpus: 1
    mem_limit: 256M
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
